version: '3.8'

services:
  ros2-sensor-sonar-aris:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - workspace=${workspace}
        - rosversion=${rosversion}
    image: soundmetrics-aris-sonar:ros2

    container_name: ${container_name}
    hostname: ${hostname}
    extra_hosts:
      - "${hostname}:127.0.0.1"
    network_mode: host
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
      - XDG_RUNTIME_DIR=/tmp/runtime-root
      - LIBGL_ALWAYS_SOFTWARE=1
      - FASTDDS_DEFAULT_PROFILES_FILE=${FASTDDS_DEFAULT_PROFILES_FILE}
    volumes:
    # In newest versions of linux distributions, the display server uses Wayland instead of X11
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ./files/src:/home/${workspace}/src
      - ./fastdds_profile.xml:/fastdds_profile.xml:ro
    stdin_open: true
    tty: true
    command: bash
