[supervisord]
nodaemon=true
logfile=/var/log/supervisor/supervisord.log
logfile_maxbytes=10MB
loglevel=info

[inet_http_server]
port=0.0.0.0:9003

[rpcinterface:supervisor]
supervisor.rpcinterface_factory=supervisor.rpcinterface:make_main_rpcinterface

[supervisorctl]
serverurl=http://localhost:9003

[program:ros2_launch]
command=/bin/bash -c "source /opt/ros/jazzy/setup.bash && source /home/ros2ws/install/setup.bash && ros2 launch soundmetrics_aris_drivers soundmetrics_aris3000_standard.launch.py"
autostart=false
autorestart=false
stdout_logfile=/var/log/supervisor/ros2_launch.log
stderr_logfile=/var/log/supervisor/ros2_launch.log
stdout_logfile_maxbytes=10MB
stderr_logfile_maxbytes=10MB
