<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>soundmetrics_aris_drivers</name>
  <version>0.1.0</version>
  <description>ROS2 driver for Sound Metrics ARIS 3000 forward-looking sonar</description>
  <maintainer email="eecs-robotics@lists.jacobs-university.de">robotics</maintainer>
  <license>MIT</license>

  <buildtool_depend>ament_python</buildtool_depend>

  <depend>rclpy</depend>
  <depend>sensor_msgs</depend>
  <depend>cv_bridge</depend>
  <depend>soundmetrics_aris_interfaces</depend>
  <depend>message_filters</depend>

  <exec_depend>ros2launch</exec_depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
