/soundmetrics_aris3000/debug: True
/soundmetrics_aris3000/use_64_bit_os: True
/soundmetrics_aris3000/local_network_interface_name: "enp4s0"
/soundmetrics_aris3000/publisher_topic: "/soundmetrics_aris3000/"
/soundmetrics_aris3000/local_ip: "169.254.7.10"
/soundmetrics_aris3000/sender_ip: "169.254.7.147"
/soundmetrics_aris3000/frame_period_sec: 0.1
/soundmetrics_aris3000/gain: 24
/soundmetrics_aris3000/frequency: 3
/soundmetrics_aris3000/focus: 380
/soundmetrics_aris3000/pulse_width: 8
/soundmetrics_aris3000/ping_mode: 9
/soundmetrics_aris3000/samples_per_beam: 512
/soundmetrics_aris3000/window_start: 1.2
/soundmetrics_aris3000/window_length: 2.0
/soundmetrics_aris3000/sample_period: 10
/soundmetrics_aris3000/cartesian_width: 350
/sound_velocity: 1488.0
# Transformation wrt vehicle frame: [x, y, z, roll, pitch, yaw] (in meters and degrees!)
/soundmetrics_aris3000/tf: [0.25, 0.0, 0.4, 80.0, 0.0, 90.0] # Pointing like a forward camera!


