debug: True
use_64_bit_os: True
local_network_interface_name: "enp4s0"
publisher_topic: "/soundmetrics_aris3000/"
frame_id: "aris3000"
frame_period_sec: 0.1
gain: 24
frequency: 3
focus: 380
pulse_width: 8
ping_mode: 9
samples_per_beam: 512
window_start: 1.2
window_length: 2.0
sample_period: 10
cartesian_width: 350
sound_velocity: 1488.0


