debug: True
use_64_bit_os: True
local_network_interface_name: "enp4s0"
publisher_topic: "/soundmetrics_aris3000/"
local_ip: "169.254.7.10"
sender_ip: "169.254.7.147"
frame_period_sec: 0.1
gain: 24
frequency: 3
focus: 380
pulse_width: 8
ping_mode: 9
samples_per_beam: 512
window_start: 1.2
window_length: 2.0
sample_period: 10
cartesian_width: 350
sound_velocity: 1488.0
# Transformation wrt vehicle frame: [x, y, z, roll, pitch, yaw] (in meters and degrees!)
tf: [0.25, 0.0, 0.4, 80.0, 0.0, 90.0] # Pointing like a forward camera!


